### ISSUE TITLE
is there a minimum certifi requirement?

### ISSUE THREAD

**Issue by jvanasco** [badkeys/badkeys#24]
apologies if this isn't a bug.

i tested this out on a spare osx machine, and got the following:

    ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)

it looks like this machine had an older certifi package form 2021 in the main library. oddly, `pip install --upgrade certifi` in the virtualenv and main library did not work, and I had to reinstall the "certificates" package.  maybe this is an oddity from the macos installer.

`https://update.badkeys.info/` seems to be serving the LetsEncrypt short chain (r3->x1).  the current certifi package works, but `certifi-2021.10.8` failed.  the isrg x1 root is in both, so this might involve the DST root that expired on 2021-09-30 still being in that trust store and somehow the library cached the DST cross-sign of X1 somewhere.  (I am not sure how, this makes little sense to me)

anyways, considering there is a paramiko requirement for scanning #17...

perhaps using a python extras might be useful for end users?

    pip install badkeys[networking] 

and then define networking to have paramiko and a minimum certifi?

    extras_require={
        "networking": ["paramiko", "certifi>X"],
    }

**Comment by hannob** [comment]
It seems you're trying to address two entirely unrelated issues here. Can we please separate that?

First of all: You've pasted an error message, but can you please clarify when you see that? When running "badkeys --update-bl"? (You're kinda implying that, as you mention the certificate for update.badkeys.info.)

The update function only uses Python's standard urllib functionality. It's true that the update.badkeys.info host uses the "short" Let's Encrypt chain, but that's by now the "default" Let's Encrypt chain which probably half of the Internet uses. If your python installation has problems accessing that, something must be extremely outdated. I'm pretty sure even certifi from 2021 should ship the ISRG root certificate.

Can you try something simple like this?
```
#!/usr/bin/python3
import urllib.request
urllib.request.urlopen('https://badkeys.info/')
```

The optional dependency issue:
paramiko is already listed as an optional dependency for the ssh keyword. So "pip install badkeys[ssh]" will install it.

**Comment by jvanasco** [comment]
1- Yes, this happened when running "badkeys --update-bl"? 

2- I will try to reset Python later to test.  I can't seem to recreate this now, even by downgrading certifi.  The core Python install is fully updated now, so I'll need to reset it and possibly set up a "long chain" site to test my cache theory against.

The Certifi in that 2021 package does have the X1 root in it, but it also has the expired DST root in it as well.  That was not removed until the 2022.05.18 release.  What I *think* happened to me, is there was a caching feature in the Python library's chain building logic, that caused it to use the "long chain" up to the expired root - instead of the short chain that was advertised.

You probably know that around the time the DST expired and LetsEncrypt pushed for a transition to the X1 root, most SSL/TLS libraries adopted a default logic of "build your own path, ignore what the server says".  A common problem that would pop up, is that browsers/libraries would have cached the signature of trust from a first site that used  `X1(cross-sign)->DST`, and the "short circuit" logic would match that cached value on `X1(self sign)` requests, then fail once they realize the trusted cert is expired.  The solution was to manually remove the DST entry from the library/os trust stores.  (IIRC,  OSX >= 10.15 needed this manual edit from their trust store for CLI tools to continue working)

**Comment by hannob** [comment]
Ok.
The idea that a chain builder would ignore the valid chain given by the server and use a cached invalid chain instead sounds unusual to me, and I wouldn't expect standard python to come with such a severe bug, but I can't rule it out.

In any case: I don't think there's much I can do here. Yeah, badkeys requires python to be able to do a standard https request, but that shouldn't require anything special.
