### ISSUE TITLE
Factoring failure when both factors in database of known primes

### ISSUE THREAD

**Issue by BenBE** [badkeys/badkeys#3]
When the user provides a key where both factors are in the set of shared primes the following code sample will always fail to factor the key even though the individual factors of the key are known.

https://github.com/badkeys/badkeys/blob/1aa40ebc04d2533e77296c1ae1ee222be4ef5b91/badkeys/rsakeys/sharedprimes.py#L19-L28

Given that storing the individual primes of the list of shared primes only doubles the space (on disk) needed to keep all the necessary information (additional factor `ceil(log2(N))` in memory), one approach would be to calculate the actual factoring tree (upon first encountering a match in the pre-check and binary-search the factors in the multiplication tree from there. This tree structure could even be pre-calculated if on-disk storage was no concern and improving factoring even in cases of single-key lookup is a concern.

**Comment by hannob** [comment]
There's some thought behind this design, which I should probably document.

The background of this vulnerability in most cases is I believe the following:
* You have an embedded device that creates an RSA key after boot
* The RNG is in a bad state (not enough entropy collected)
* Prime 1 is generated
* The RNG improves (more entropy)
* Prime 2 is generated

In this case you always have a good prime and a bad prime, you won't have a key that's the product of 2 bad primes.
This is btw also the reason why I only have the gcds in the factor collection and not the corresponding other primes in the vulnerable moduli.

While this is only one case how this vulnerability can surface, based on the analysis I know about this vuln it's the most likely one. So this design should in most cases be able to break keys affected by this vuln.

Another consideration is that my main goal with badkeys is to detect vulnerable keys. I do calculate the factorization if easily possible, but it's not the main goal. If I know a key is bad that's in most cases good enough.

**Comment by BenBE** [comment]
ACK. I know the vul you are testing for with that check. And if the brokenness of the RNG (initialization) really only affects one of the primes the above code works as intended.

The edge case I wanted to document with this issue is only when you happen to get unlucky and generate two bad primes for your key and thus even though you could calculate the key with information you have (the (pre-multiplied list of) bad primes) you fail to actually arrive at the factorization.

This doesn't impact the ability to flag that key as bad (that part still works). It just fails in a case where it (easily) could do better.

NB: Doesn't hurt to reference the "boot time entropy hole" and "[mining your P's and Q's](https://www.cs.umd.edu/class/fall2017/cmsc818O/papers/ps-and-qs.pdf)".

**Comment by hannob** [comment]
Mining your Ps and Qs is referenced on the webpage:
https://badkeys.info/docs/commonprimes.html

I think for the code I'll just leave it for now. It's okay that in cornercases the factoring won't work. Though I will likely at some point when I have cleaned up things a bit publish the raw gcds itself, so in cases someone wants to factor the data is available.
