### ISSUE TITLE
Another OS-Specific Bug

### ISSUE THREAD

**Issue by dchampion** [badkeys/badkeys#5]
The following code (line 65) raises an exception in Windows:

https://github.com/badkeys/badkeys/blob/c8cbc244f645cfcc54244fa4ea7722cd3f39ce22/badkeys/allkeys/block.py#L64-L65

Pretty sure the fix is this:

<pre>
with open(f"{cachedir}blocklist.dat", "rb") as f:
    _bldata = mmap.mmap(fileno=f.fileno(), length=0, access=mmap.ACCESS_READ)
</pre>

Although perhaps there is a specific reason you chose the non-Windows-specific protection?

In any case, any code that attempts to open the file in Windows fails.

**Comment by hannob** [comment]
Fixed (after 2nd try...):
https://github.com/badkeys/badkeys/commit/71cef8b3cee55a77194216bd40f6f5ed514b533e
https://github.com/badkeys/badkeys/commit/fe8659693e1443bc1aefd1a2f00c5885b21b831a

Now the CI runs without errors in Windows, so I guess we can claim Windows compatibility 🥳

**Comment by dchampion** [comment]
Thanks, Hanno! This project represents valuable work; please keep it up :)
